# Generated by Django 5.2.6 on 2025-09-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='MailModel',
        ),
    ]
