# Generated by Django 5.2.6 on 2025-09-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_delete_customer_delete_mailmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=255)),
                ('your_email', models.EmailField(max_length=254)),
                ('your_message', models.TextField()),
                ('sended_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
