# Generated by Django 5.2.8 on 2025-11-18 02:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_title', models.CharField(max_length=255)),
                ('deadline_date', models.DateField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
