# Generated by Django 5.2.8 on 2025-11-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_carriermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carriermodel',
            name='carrier_image',
            field=models.ImageField(blank=True, null=True, upload_to='Admin/CarrierImages/'),
        ),
    ]
