# Generated by Django 5.2.8 on 2025-11-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_carriermodel_carrier_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carriermodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
